apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-s3ye
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-s3ye
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-s3ye
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-s3ye
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-s3ye
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-izul-tenant/rhtap-demo-app/hacbs-test-project-s3ye@sha256:91d7d6432412ce9060c2cafbc69431cbbabdbea45d21fc1367794599936e48fb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
